### ISSUE TITLE
Some files outdated?

### ISSUE THREAD

**Issue by k-tipp** [practikpharma/PGxO#3]
Hi,

is the PHARE version on https://bioportal.bioontology.org/ontologies/PHARE/?p=summary the latest version? Because I failed to find the following class &lt;http://www.stanford.edu/~coulet/phare.owl#Variant&gt; mentioned in pgxo.owl. Also it seem like the PHARE ontology cannot be accessed on http://www.stanford.edu/~coulet/phare.owl.

Thank you very much and kind regards

k-tipp

**Comment by coulet** [comment]
Hi there, 
the URI you mention are not dereferenced, and it seems that the Bioportal has issues at parsing PHARE.
Please download the .owl file of PHARE on the Bioportal, you can open it with Protege or from your code with your favorite owl parsing library.
You should be able to find the concept this way. 
Best,
Adrien

**Comment by k-tipp** [comment]
Thank you very much for the quick response.
The problem is that the class #Variant has multiple labels and a random one is selected by Bioportal. It can be found as "frame-shift" at the moment.
